#!/bin/bash

COUNT=0
CURRENT_DIR="$PWD"
PD="build_tools/patches"
PATCHES=(
'art				art.patch'
'external/icu                   external_icu.patch'
'external/tinyalsa              external_tinyalsa.patch'
'frameworks/av			frameworks_av.patch'
'frameworks/av                  audio_fix2.patch'
'frameworks/base		frameworks_base.patch'
'frameworks/native		frameworks_native.patch'
'frameworks/native              fnw.patch'
'frameworks/native              fnw2.patch'
'frameworks/opt/telephony	frameworks_opt_telephony.patch'
'hardware/broadcom/libbt	hardware_broadcom_libbt.patch'
'hardware/libhardware           audio_fix.patch'
'packages/inputmethods/LatinIME packages_inputmethods_LatinIME.patch'
'packages/services/Telephony	packages_services_Telephony.patch'
'system/core			system_core.patch'
'system/media                   system_media.patch'
'vendor/cm                      kernel.patch'
'vendor/cm			vendor_cm.patch'
)

while [ "x${PATCHES[COUNT]}" != "x" ]
do
	CURRENT="${PATCHES[COUNT]}"
	FOLDER=`echo "$CURRENT" | awk '{print $1}'`
	PATCH=`echo "$CURRENT" | awk '{print $2}'`

	cd "$FOLDER"
	echo Discarding previous Patches
	repo sync .
	echo Patching "$FOLDER" ...
	git am -3 "$CURRENT_DIR/$PD/$PATCH"
	cd "$CURRENT_DIR"

	COUNT=$(($COUNT + 1))
done
